"""Precomputed trending skills aggregated from all seed files.

Auto-generated by scripts/bake_seed_skills.py — do not edit manually.
Regenerate after adding/updating seeds:
    python scripts/bake_seed_skills.py
"""
TRENDING_SKILLS = [
    {"skill": "Software Development", "count": 676},
    {"skill": "Programming", "count": 497},
    {"skill": "Engineering", "count": 68},
    {"skill": "Software Engineering", "count": 63},
    {"skill": "Python", "count": 33},
    {"skill": "Distributed Systems", "count": 25},
    {"skill": "Leadership", "count": 23},
    {"skill": "Kubernetes", "count": 20},
    {"skill": "Engineering Management", "count": 17},
    {"skill": "Java", "count": 17},
    {"skill": "Go", "count": 16},
    {"skill": "Full Stack", "count": 11},
    {"skill": "Machine Learning", "count": 10},
    {"skill": "Agile Development", "count": 8},
    {"skill": "Kafka", "count": 8},
    {"skill": "Go/Golang", "count": 7},
    {"skill": "Typescript", "count": 6},
    {"skill": "Frontend", "count": 6},
    {"skill": "Management", "count": 6},
]
